bucket:
  strip: 1

packages:
   - name: s
     actions:
      - name: url
        limits:
          timeout: 60000
        environment:
          DB_Username: ${DB_Username}
          DB_Password: ${DB_Password}
          DB_ClusterUri: "${DB_ClusterUri}"
          DB_Name: ${DB_Name}
          DB_Table: ${DB_Table}
          BASE_URL: ${BASE_URL}
        
        
